# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2177e2c8fd840c7e8b5ef93dc2c3b3cf2d4e9a19a00e126d008689094384092057aab9dd31a89e2e7e84520acb2196986c25ce682620321e23441f2d07ccb5

test:
  secret_key_base: f07ded45cf790a2794abf84a667a4f310fcf65dd45c59e2f61b983584c25ed4bac7c044ea55675d4d448621ade84706fd075e68cc924186dfc10043221036e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
